### ISSUE TITLE
LINUX下如何使用

### ISSUE THREAD

**Issue by dwzn** [valuex/GoldenDict2Anki#1]
你好，
我需要在LINUX下使用，能否把gd2anki.exe开源，
或者您可以移植到LINUX下，如果您不方便，
能否给一个源码，我来做移植的工作，
完成后再分享回来。
谢谢！

**Comment by Conanzhou** [comment]
请问有成功移植吗？谢谢

**Comment by valuex** [comment]
Github仓库中有上传源码，在Linux上面应该也是可以运行的，知乎上面的读者应该尝试成功了。
![image](https://user-images.githubusercontent.com/3627812/110198808-0e957b80-7e90-11eb-91cf-f7f0947489aa.png)

**Comment by choyy** [comment]
@Conanzhou 只有那个发出声音的`winsound`的东西在Linux下不能用，把相关的东西删掉就能用了
我的Fork就直接删掉了：https://github.com/choyy/GoldenDict2Anki
