### ISSUE TITLE
No cards were added into the NewWords Deck.

### ISSUE THREAD

**Issue by realasking** [valuex/GoldenDict2Anki#2]
Dear author,
I'm so glad to see this project you made. However, when I finished configuring Goldendict and Anki, I failed to get the queried word added into the newly created "NewWords" Deck.
No error message was output, and just nothing happened after the word was shown in Goldendict.
The configurations are listed below.
1.In Goldendict
![gd2anki_GD](https://user-images.githubusercontent.com/4168843/106872330-243b4800-670e-11eb-84bd-a7c064e8443b.jpg)
2.The dictionary
![gd2anki_dict](https://user-images.githubusercontent.com/4168843/106872502-56e54080-670e-11eb-9ec3-bc95bff72f01.jpg)
The db files are automatically generated using FastWQ, as your suggested mdx-server only exported a db file with 0 KB.
3.The configuration of Anki
![gd2anki_anki](https://user-images.githubusercontent.com/4168843/106873262-3cf82d80-670f-11eb-8a9a-83b3e8d17300.jpg)
Expect and appreciate your help. 
Thank you.

**Comment by valuex** [comment]
可以用我最新增加的配置程序检查下Anki 中的配置:
这几个字段，在Anki中一定要配置正确

- deckName -- NewWords

- modelName--NewWordsType

- fields --  Front/Back

```
"deckName": "NewWords",
        "modelName": "NewWordsType",
        "fields": {
            "Front": "%s",
            "Back": "%s"
        }
```

**Comment by ichenh** [comment]
@realasking 我遇到同样的问题。试一下将 Anki 的界面语言改成英文。
