### ISSUE TITLE
通过了设置检查，但是仍然报错

### ISSUE THREAD

**Issue by wanghuibin0** [valuex/GoldenDict2Anki#6]
在goldendict中查词报错：
![image](https://user-images.githubusercontent.com/14231615/120258947-8d4e5900-c2c5-11eb-9d92-40d5551daaa4.png)

下载的是最新的release。

在命令行运行设置检查：
![image](https://user-images.githubusercontent.com/14231615/120258893-73147b00-c2c5-11eb-893d-324cc5cf2694.png)

其中有个很奇怪的现象：
我在命令行中单独用GD2Anki.exe查词，如上图中的`./GD2Anki.exe hello`，返回了一串数字，貌似是能成功的，但是一旦我在goldendict中用相同的词查过一遍，除了goldendict直接报错外，再次从命令行运行`./GD2Anki.exe hello`，就没有那串数字了。

**Comment by huitengxile** [comment]
我也遇到了类似的问题，在goldendict路径设置的时候，%GDWORD%前面加了个空格，然后好了，，，，，
再次查询不再返回数字，我猜是因为词条已经被添加到anki里面了

**Comment by huitengxile** [comment]
有点烦的一点是，每添加一个新词会“滴”响一下。。。。

**Comment by valuex** [comment]
> 有点烦的一点是，每添加一个新词会“滴”响一下。。。。

已经关闭了这个声音。
