### ISSUE TITLE
不支持构词法

### ISSUE THREAD

**Issue by nankeys** [valuex/GoldenDict2Anki#7]
如果划词选中某个词或者查询如“names”，虽然GoldenDict可以显示正确的单词解释，但是程序会失败无法自动添加“name”作为ANKI的单词卡片，会报如下错误：

> 查询错误：程序已崩溃。 [8860] Failed to execute script GD2Anki Traceback (most recent call last): File "GD2Anki.py", line 71, in <module> IndexError: list index out of range

**Comment by valuex** [comment]
V1.3 已经支持，取决于定义的词典，如果词典中能查到对应的解释，就能够导入到Anki中。
